url: "https://adamleif.net"
enforce_ssl: adamleif.net
baseurl: ""
livereload: true
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
include: 
  - pages
defaults:
  - 
    scope:
      path: ''
      type: pages
    values:
      layout: default 
      permalink: /:basename.html